// src/components/project.tsx
import type { Project as IProject } from "@data/projects";

interface Props {
  project: IProject;
}

export default function Project({ project }: Props) {
  const { image, title } = project;

  return (
    <div className="border rounded-lg">
      <img className="rounded-t-lg aspect-video" src={image} alt={title} loading="lazy" decoding="async" />
      <h2>{title }</h2>
    </div>
  );
}

// src/components/project.svelte
<script lang="ts">
  import { type Project } from "@data/projects";

  export let project: Project;

  const { image, title } = project;
</script>

<li class="border rounded-lg">
  <img
    class="rounded-t-lg aspect-video"
    src={image}
    alt={title}
    loading="lazy"
    decoding="async"
  />
  <h2>{title}</h2>
</li>
