// src/components/projects_list.tsx
import Project from "@components/project";
import { type Project as IProject } from "@data/projects";

interface Props {
  projects: IProject[];
}
export default function ProjectsList({ projects }: Props) {
  return (
    <ul className="grid gap-5 grid-cols-1 md:grid-cols-2">
      {projects.map((project) => (
        <Project project={project} key={project.id} />
      ))}
    </ul>
  );
}

// src/components/projects_list.svelte
<script lang="ts">
  import Project from "@components/project.svelte";
  import { type Project as IProject } from "@data/projects";

  export let projects: IProject[];
</script>

<ul class="grid gap-5 grid-cols-1 md:grid-cols-2">
  {#each projects as project (project.id)}
    <Project {project} />
  {/each}
</ul>
