// src/components/scroll_top_button.svelte
<script>
  import { scale } from "svelte/transition";

  let prevY = 0;
  let show = false;

  function handleScroll() {
    if (scrollY < 100 || scrollY > prevY) {
      show = false;
    } else {
      show = true;
    }
    prevY = scrollY;
  }
</script>

<svelte:window on:scroll={handleScroll} />

{#if show}
  <button
    class="fixed right-6 bottom-10 p-4 leading-4 rounded-full bg-primary dark:bg-primary-dark text-white"
    title="scroll to top"
    type="button"
    transition:scale={{ duration: 300 }}
    on:click={() => {
      scrollTo({ top: 0, behavior: "smooth" });
    }}
  >
    <span class="icon icon-arrow-up"></span>
  </button>
{/if}

// src/components/scroll_top_button.tsx
import { useEffect, useRef, useState } from "react";

export default function scrollTopButton(props) {
  const [show, setShow] = useState(false);
  const prevScrollY = useRef(0);

  useEffect(() => {
    const handleWindowScroll = () => {
      const currentScrollY = scrollY;

      if (currentScrollY < 100 || currentScrollY > prevScrollY.current) {
        // User is still at the top of the page or scrolling down
        setShow(false);
      } else {
        // User is scrolling up
        setShow(true);
      }

      prevScrollY.current = currentScrollY;
    };

    window.addEventListener("scroll", handleWindowScroll);

    return () => {
      window.removeEventListener("scroll", handleWindowScroll);
    };
  }, []);

  function handleClick() {
    scrollTo({ top: 0, behavior: "smooth" });
  }

  return (
    <button
      className={`fixed right-6 bottom-10 p-3 bg-primary dark:bg-primary-dark text-white rounded-full ${
        show ? "visible animate-zoom-in" : "invisible animate-zoom-out"
      }`}
      type="button"
      title="scroll to top"
      onClick={handleClick}
    >
      {props.icon}
    </button>
  );
}
