// src/components/theme_menu.tsx
import type { IconType } from "react-icons";
import {
  BsCaretDownFill,
  BsCircleHalf,
  BsMoonStarsFill,
  BsSunFill,
} from "react-icons/bs";
import type { Theme } from "src/env";
import { useEffect, useRef, useState } from "react";

const getThemeIcon = (Icon: IconType) => <Icon />;

const themeIcons: Map<Theme, IconType> = new Map([
  ["dark", BsMoonStarsFill],
  ["light", BsSunFill],
  ["system", BsCircleHalf],
]);

export default function ThemeMenu() {
  const [isOpen, setIsOpen] = useState(false);
  const [activeTheme, setActiveTheme] = useState<Theme>("system");

  const menuRef = useRef(null);

  useEffect(() => {
    const storedTheme = localStorage.getItem("theme") as Theme | null;
    const darkQuery = window.matchMedia("(prefers-color-scheme: dark)");

    darkQuery.addEventListener("change", handleSystemTheme);

    function handleSystemTheme(event: MediaQueryListEvent) {
      if (!storedTheme) {
        setTheme(event.matches ? "dark" : "light");
      }
    }
    return darkQuery.removeEventListener("change", handleSystemTheme);
  }, []);

  function toggleMenu() {
    setIsOpen(!isOpen);
    isOpen && menuRef.current.focus();
  }

  function handleClick(event: MouseEvent) {
    const theme = event.target.getAttribute("data-theme") as Theme;

    setActiveTheme(theme);
    setTheme(theme);
    setIsOpen(false);

    if (theme === "light" || theme === "dark") {
      localStorage.setItem("theme", theme);
    } else {
      localStorage.removeItem("theme");
    }
    console.log(window.matchMedia("(prefers-color-scheme: dark)").matches);
  }

  function setTheme(theme: Theme) {
    if (
      theme === "dark" ||
      (theme === "system" &&
        window.matchMedia("(prefers-color-scheme: dark)").matches)
    ) {
      document.documentElement.classList.add("dark");
    } else {
      document.documentElement.classList.remove("dark");
    }
  }

  return (
    <div className="relative">
      <button
        className="inline-flex items-center gap-2 p-2 border rounded-lg bg-primary text-white"
        type="button"
        onClick={toggleMenu}
      >
        {getThemeIcon(themeIcons.get(activeTheme)!)}
        <span className="sr-only" aria-live="polite">
          {activeTheme}
        </span>
        <BsCaretDownFill
          className={`transition-transform duration-300 ${
            isOpen ? "rotate-180" : ""
          }`}
        />
      </button>
      <ul
        className={`absolute md:right-0 p-1 mt-1 space-y-1 border rounded-md ${
          isOpen ? "" : "hidden"
        }`}
        role="menu"
        ref={menuRef}
      >
        {Array.from(themeIcons.entries()).map(([theme, Icon]) => (
          <li role="presentation" key={theme}>
            <button
              className={`inline-flex items-center gap-2 w-full py-1 px-2 rounded-md hover:bg-primary hover:text-white dark:hover:bg-primary-dark capitalize ${
                theme === activeTheme ? "bg-primary text-white" : ""
              }`}
              data-theme={theme}
              type="button"
              role="menuitem"
              onClick={handleClick}
            >
              <Icon />
              {theme}
            </button>
          </li>
        ))}
      </ul>
    </div>
  );
}

// src/components/theme_menu.svelte
<script lang="ts">
  import { clickOut } from "src/utils";

  const themeIcons = new Map([
    ["dark", "moon-stars"],
    ["light", "sun"],
    ["system", "circle-half"],
  ]);

  let menuIsOpen = false;
  let activeTheme = "system";
  let darkQuery = window.matchMedia("(prefers-color-scheme: dark)");

  setTheme(activeTheme);

  $: {
    if (activeTheme === "system") {
      darkQuery.addEventListener("change", handleDarkQuery);
    }
  }

  function handleChange() {
    menuIsOpen = false;
    switch (activeTheme) {
      case "dark":
      case "light":
        localStorage.setItem("theme", activeTheme);
        setTheme(activeTheme);
        break;
      case "system":
        localStorage.removeItem("theme");
        setTheme(darkQuery.matches ? "dark" : "light");
        break;
      default:
        break;
    }
  }

  function setTheme(theme) {
    if (
      localStorage.theme === "dark" ||
      (!("theme" in localStorage) &&
        window.matchMedia("(prefers-color-scheme: dark)").matches)
    ) {
      document.documentElement.classList.add("dark");
    } else {
      document.documentElement.classList.remove("dark");
    }
  }

  function handleDarkQuery(this: MediaQueryList, event: MediaQueryListEvent) {
    const systemTheme = event.matches ? "dark" : "light";
    console.log(systemTheme);
  }
</script>

<div class="ms-auto relative">
  <button
    class="inline-flex items-center gap-1 p-2 leading-4 border rounded-lg bg-primary dark:bg-primary-dark text-white"
    on:click={() => {
      menuIsOpen = !menuIsOpen;
    }}
  >
    <span class={`icon icon-${themeIcons.get(activeTheme)}`}></span>
    <span
      class={`icon icon-caret-down transition-transform duration-300 ${menuIsOpen ? "rotate-180" : ""}`}
    ></span>
  </button>
  <div
    class={`
    absolute right-0 flex flex-col p-1 mt-1 border rounded-md space-y-2
    bg-white dark:bg-dark
    ${!menuIsOpen ? "hidden" : ""}
   `}
    use:clickOut
    on:clickout={handleChange}
  >
    {#each themeIcons as [theme, icon] (theme)}
      <label
        class="inline-flex justify-between items-center gap-1 p-2 rounded-lg cursor-pointer capitalize hover:bg-gray-300 dark:hover:bg-gray-600"
      >
        <span class={`icon icon-${icon}`}></span>
        {theme}
        <input
          class="appearance-none"
          name="theme"
          value={theme}
          type="radio"
          bind:group={activeTheme}
          on:change={() => (menuIsOpen = false)}
        />
      </label>
    {/each}
  </div>
</div>

<style lang="scss">
  .wrapper {
    &-inner {
      margin: 0;
    }
  }
</style>
